src/main/java/com/maxmind/db/Decoder.java

The library creates an excessive amount of garbage. To address this, a thorough redesign would be needed (see issue #13). In the meantime, here's a small patch that reduces allocations around Decoder#decodeString, incidentally also improving performance by 10-20%.

Optimizations for String decoding

---

src/main/java/com/maxmind/db/Decoder.java

ObjectMapper is in fact thread-safe (see [javadoc](https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/ObjectMapper.html)).
Yields a ~3-5% improvement in Benchmark, improving issue #13.

perf: reuse ObjectMapper

---

src/main/java/com/maxmind/db/Decoder.java

Inlined and optimized sizeFromCtrlByte and decodePointer. Reduces object churn on return values (see #13) and also improves JIT inlining patterns.
Net speedup on benchmark 10-15%.

Inline and optimize some decoding methods to improve performance

---

sample/Benchmark.java

Benchmark results might vary based on a number of factors. I tend to select a fixed random seed so the test run is repeatable. Also, I disable Intel's Turbo Boost feature, so it doesn't vary the CPU frequency with overclocking. I run the benchmark loop multiple times, so the JIT is warmed up. With these tweaks, you get more consistent and meaningful results.

Improve benchmark

---

src/test/java/com/maxmind/db/DecoderTest.java
src/test/java/com/maxmind/db/MultiThreadedTest.java
src/test/java/com/maxmind/db/PointerTest.java
src/test/java/com/maxmind/db/ReaderTest.java

Some minor code cleanup while reviewing the unit test code.

Unit test cleanup

---

src/main/java/com/maxmind/db/Decoder.java
src/main/java/com/maxmind/db/Reader.java
src/test/java/com/maxmind/db/DecoderTest.java
src/test/java/com/maxmind/db/PointerTest.java

The ByteBuffer itself keeps track of the read position. Reduces object churn (#13), also simplifies the code.

eliminate Decoder.Result objects

---

sample/Benchmark.java
src/main/java/com/maxmind/db/NoCache.java
src/main/java/com/maxmind/db/Reader.java
src/test/java/com/maxmind/db/PointerTest.java

minor code cleanup

---

pom.xml
src/main/java/com/maxmind/db/CHMCache.java
src/main/java/com/maxmind/db/Decoder.java

Note, this requires Jackson 2.7.x.
Refs #13.

immutable ContainerNodes to avoid deep copies

---

pom.xml

to align with the same version that is being used by MaxMind GeoIP2 API 2.10.0

Update jackson-databind to version 2.9.2

---

CHANGELOG.md
src/main/java/com/maxmind/db/Decoder.java
src/test/java/com/maxmind/db/DecoderTest.java

See https://github.com/maxmind/GeoIP2-java/issues/181

Correctly decode strings that are between 157 and 284 bytes long

---

src/main/java/com/maxmind/db/BufferHolder.java

This does not change any behaviour, but it would
prevent bugs in the future if something tries to write to the buffer.
If fileMode is MEMORY_MAPPED, this would already fail, so
this extra protection only really applies to the MEMORY mode.

Explicitly make the ByteBuffer content readonly

---

CHANGELOG.md
pom.xml
src/main/java/com/maxmind/db/BufferHolder.java

- Upgrade Jackson Databind
- Remove use of synchronized around duplicate(). Closes #65, #69, #72.

Remove synchronized

---

src/main/java/com/maxmind/db/CHMCache.java
src/main/java/com/maxmind/db/CacheKey.java
src/main/java/com/maxmind/db/Decoder.java
src/main/java/com/maxmind/db/NoCache.java
src/main/java/com/maxmind/db/NodeCache.java
src/test/java/com/maxmind/db/ReaderTest.java

Previously the lack of this meant that we'd not decode to the expected
type in cases such as List<Foo>. This was because Type wasn't passed
through given the call to decode() didn't include it.
This also now takes into account the class and type in the cache key,
where previously we could behave return a different class than expected
if deserializing into two different classes.

Pass Type parameter through when loading via cache

---

src/main/java/com/maxmind/db/Decoder.java
src/test/java/com/maxmind/db/ReaderTest.java

This lead to issues when decoding primitives from the cache, such as
booleans: Cannot cast java.lang.Boolean to boolean. The non cache path
worked because the Boolean would be unboxed transparently.

Do not cast() when retrieving from cache

---

src/main/java/com/maxmind/db/CHMCache.java
src/main/java/com/maxmind/db/CacheKey.java
src/main/java/com/maxmind/db/DecodedValue.java
src/main/java/com/maxmind/db/Decoder.java
src/main/java/com/maxmind/db/NoCache.java
src/main/java/com/maxmind/db/NodeCache.java
src/main/java/com/maxmind/db/Reader.java
src/test/java/com/maxmind/db/DecoderTest.java
src/test/java/com/maxmind/db/ReaderTest.java

This provides us with more flexibility to change what is cached.

Add cache value class

---

pom.xml

This is because I am seeing
java.lang.NoSuchMethodError:
java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
when running on Java 8 when using this in GeoIP2-java.
See https://github.com/eclipse/jetty.project/issues/3244.

Specify java release version to use when building

---

CHANGELOG.md
README.md
pom.xml

- Set release date and fix typo
- update version number in README.md
- Revert "Stop using mvn to initialize/update submodule"
- [maven-release-plugin] prepare release v2.1.0
- [maven-release-plugin] prepare for next development iteration

Release 2.1.0

---

src/main/java/com/maxmind/db/Decoder.java
src/test/java/com/maxmind/db/ReaderTest.java

This PR aims to improve the error handling of Decoder.decodeMapIntoMap() by:
- Catching ClassCastException and transform into DeserializationException with an appropriate message
This logic should be in line with the error handling seen in Decoder.decodeMapIntoObject().
ReaderTest has been extended with a new test; this exercises the handling a datatype mismatch between the schema in the MMDB file and the provided class to populate

Issue #126 - Improve error handling in Decoder.decodeMapIntoMap() 

---

pom.xml

Dependabot will stop looking for maven dependencies once it finds a repository that returns any number of results, even if none of those results match the requested version. This removes the ossrh repository because it brings in snapshot repositories that prevent dependabot from falling back to the central repository. See: dependabot/dependabot-core#5872

Fix dependabot snapshots

---

dev-bin/release.sh
pom.xml
src/main/java/com/maxmind/db/Networks.java
src/main/java/com/maxmind/db/Reader.java
src/test/java/com/maxmind/db/DecoderTest.java
src/test/java/com/maxmind/db/MultiThreadedTest.java
src/test/java/com/maxmind/db/NetworkTest.java
src/test/java/com/maxmind/db/PointerTest.java
src/test/java/com/maxmind/db/ReaderTest.java

- Don't unnecessarily specify types
- Switch to JUint 5

Switch to JUnit 5

---

pom.xml

- Do not run exec-maven-plugin on Windows
- Remove active-on-jdk-9-plus profile

Upgrade exec-maven-plugin

---

CHANGELOG.md
README.md
dev-bin/release.sh
pom.xml

- **Set release date**
- **Update Maven version**
- **update version number in README.md**
- **[maven-release-plugin] prepare release v3.1.1**
- **[maven-release-plugin] prepare for next development iteration**
- **Update for path change**

Release 3.1.1

---

src/main/java/com/maxmind/db/Decoder.java
src/test/java/com/maxmind/db/DecoderTest.java
src/test/java/com/maxmind/db/TestDecoder.java

Remove pointerTestHack
- factor out pointer logic into a method
- create a subclass of `Decoder` for tests
- move test logic to test subclass

Remove pointerTestHack

---

src/test/java/com/maxmind/db/DecoderTest.java

Remove the creation of temp files in tests. `Decoder` depends on `ByteBuffer` so we can use an on-heap buffer. The comment talks about Java 6 compatibility but the code depends on Java 11.

Remove temp file creation for tests

---

CHANGELOG.md
README.dev.md
README.md
dev-bin/release.sh
pom.xml

- **Release using Central Portal**
- **Add release notes for code-cleanup PRs**
- **Preparing for 3.2.0**
- **Fix directory for apidocs**

Release via Central Portal
